server:
 port: 8099
spring:
 application:
  name: User-Service
 datasource:
  url: jdbc:mysql://localhost:3306/userservice
  username: root
  password: root@123
  driver-class-name: com.mysql.cj.jdbc.Driver
 jpa:
  hibernate: 
   ddl-auto: update
  show-sql: true
 config: 
  import: optional:configserver:http://localhost:9090
  
management:
 health:
  circuitbreakers:
   enabled: true
 endpoint:
  health:
   show-details: always


resilience4j:
  circuitbreaker:
   instances:
    ratingHotelBreaker:
     registerHealthIndicator: true
     eventConsumerBufferSize: 10
     failureRateThreshold: 50
     minimumNumberOfCalls: 5
     automaticTransitionFromOpenToHalfOpenEnabled: true
     waitDurationInOpenState: 6s
     permittedNumberOfCallsInHalfOpenState: 3
     slidingWindowSize: 10
     slidingWindowType: COUNT_BASED
#retry:
# instances:
#  ratingHotelService:
#   max-attempts: 3
#   wait-duration: 3s